src/interfaces/google.js, src/interfaces/index.js
=> 添加谷歌翻译（免费接口，请求不能太频繁，支持中英）

src-tauri/src/window.rs, src/windows/Translator/components/SourceArea/index.jsx
=> feat: 添加增量翻译功能

src/interfaces/caiyun.js, src/interfaces/deepl.js, src/interfaces/openai.js
=> feat: DeepL支持设置API Key

src/windows/Config/index.jsx, src/windows/Config/pages/AppConfig/index.jsx, src/windows/Translator/components/SourceArea/index.jsx, src/windows/Translator/components/TargetArea/index.jsx
=> feat: 支持设置翻译窗口源文本和译文的字体大小

src/windows/Config/index.jsx
=> feat: auto scroll top

src/windows/Translator/components/TopBar/index.jsx, src/windows/Translator/index.jsx
修复了Windows下划词窗口无法拖动的问题。
由于 Tauri 没有 dragging 结束事件，所以使用 debounce 方式处理 onMoved 事件实现。
#36
=> fix: 修复Windows下划词窗口无法拖动

src-tauri/src/window.rs
#94 
通过position拿到的值是虚拟屏幕的坐标，可以用这个做边界判断。
=> fix: 多屏幕窗口边界问题

src-tauri/src/window.rs, src/windows/Screenshot/index.jsx
=> fix: Mult-Screen Support

.github/workflows/package.yml
This reverts commit aca6a9268520e3ac86a320f28ff6f1271712d2c4.
=> Revert "add linux x86 support (#222)"

.github/workflows/package.yml
I have tested, see https://github.com/liudonghua123/pot-desktop/actions/runs/5262998604/jobs/9512737960.
=> feat: add arm target support

src-tauri/src/trayicon.rs, src-tauri/src/window.rs, src/windows/Config/components/ConfigList/style.css, src/windows/Config/components/SideBar/style.css, src/windows/Config/components/TopBar/index.jsx, src/windows/Config/components/TopBar/style.css, src/windows/Config/index.jsx, src/windows/Config/style.css, src/windows/Ocr/components/TextArea/index.jsx, src/windows/Ocr/components/TopBar/index.jsx, src/windows/Ocr/components/TopBar/style.css, src/windows/Ocr/index.jsx, src/windows/Ocr/style.css
=> refactor: custom title bar for ocr window

src/windows/Translator/components/SourceArea/index.jsx
=> fix: read clipboard

src/windows/Translator/components/TargetArea/index.jsx
=> refactor: copy source when source change

src-tauri/src/window.rs
=> fix: mult-screen window position

src-tauri/src/trayicon.rs
=> fix: Translate Tray Menu to Brazilian Portuguese

src/interfaces/deepl.js
=> fix: DeepL Error when translate to portuguese

src/windows/Translator/index.jsx
=> fix: Hide language selector error

README.md
Improve README.md - Installation - Linux - Arch/Manjaro according to the Chinese documentation
=> doc: Improve README.md

pnpm-lock.yaml, public/tatoeba.svg, src/interfaces/index.js, src/interfaces/tatoeba.js, src/locales/en_US.json, src/locales/pt_BR.json, src/locales/ru_RU.json, src/locales/zh_CN.json, src/locales/zh_TW.json
=> feat: Add Tatoeba Support

src/windows/Translator/components/SourceArea/index.jsx
=> fix: delete newline failed

package.json, src-tauri/tauri.conf.json, src/i18n/locales/en_US.json, src/i18n/locales/pt_BR.json, src/i18n/locales/zh_CN.json, src/window/Config/pages/History/index.jsx, src/window/Config/pages/Service/Collection/ConfigModal/index.jsx, src/window/Config/pages/Service/Collection/SelectModal/index.jsx, src/window/Config/pages/Service/Collection/ServiceItem/index.jsx, src/window/Config/pages/Service/Collection/index.jsx, src/window/Config/pages/Service/Recognize/ConfigModal/index.jsx, src/window/Config/pages/Service/Recognize/SelectModal/index.jsx, src/window/Config/pages/Service/Recognize/ServiceItem/index.jsx, src/window/Config/pages/Service/Recognize/index.jsx, src/window/Config/pages/Service/Translate/ConfigModal/index.jsx, src/window/Config/pages/Service/Translate/SelectModal/index.jsx, src/window/Config/pages/Service/Translate/ServiceItem/index.jsx, src/window/Config/pages/Service/Translate/index.jsx, src/window/Config/pages/Service/Tts/ConfigModal/index.jsx, src/window/Config/pages/Service/Tts/SelectModal/index.jsx, src/window/Config/pages/Service/Tts/ServiceItem/index.jsx, src/window/Config/pages/Service/Tts/index.jsx, src/window/Recognize/ControlArea/index.jsx, src/window/Recognize/TextArea/index.jsx, src/window/Translate/components/SourceArea/index.jsx, src/window/Translate/components/TargetArea/index.jsx
It seems that this should be 'builtin' instead of 'buildin'. And recommend using [streetsidesoftwarevscode-spell-checker A simple source code spell checker for code](https://github.com/streetsidesoftware/vscode-spell-checker) to check code spell
=> chore: fix typo

src/services/translate/deepl/index.jsx
https://www.deepl.com/docs-api/
=> src/services/translate/deepl/index.jsx: Fix DeepL Free API

src/services/recognize/baidu/Config.jsx, src/services/recognize/baidu_accurate/Config.jsx, src/services/recognize/baidu_img/Config.jsx, src/services/recognize/iflytek/Config.jsx, src/services/recognize/iflytek_intsig/Config.jsx, src/services/recognize/iflytek_latex/Config.jsx, src/services/recognize/simple_latex/Config.jsx, src/services/recognize/tencent/Config.jsx, src/services/recognize/tencent_accurate/Config.jsx, src/services/recognize/tencent_img/Config.jsx, src/services/recognize/volcengine/Config.jsx, src/services/recognize/volcengine_multi_lang/Config.jsx
Following #491, this PR refactored the config modal component in the recognize config page.
I've added and tested these services and they all work well.
=> refactor: improve ux of config modal in the recognize config page

README.md, src/services/collection/anki/index.jsx, src/window/Translate/components/TargetArea/index.jsx
=> fix bug: when add object to anki, the back turns out to [Object Object]

package.json, pnpm-lock.yaml, src/window/Translate/components/TargetArea/index.jsx
添加翻译结果展开的动画 效果如下
https://github.com/pot-app/pot-desktop/assets/98862205/cdbb2f66-a996-4f31-827f-94ac09696b1e
=> feat: add animations for translation card

src/style.css
=> feat: 修复windows系统滚动到顶部或底部后出现空白边缘

src/services/translate/openai/Config.jsx
Repair openai translation prompt description
=> fix: repair openai translation prompt description

src/services/translate/chatglm/Config.jsx, src/services/translate/chatglm/index.jsx, src/services/translate/openai/index.jsx, src/window/Translate/components/TargetArea/index.jsx
=> update chatglm translate service
